### ISSUE TITLE
Infinite build loop with CMake

### ISSUE THREAD

**Issue by ShawnHymel** [edgeimpulse/inferencing-sdk-cpp#7]
From a user. I have not verified this.

> Hi edge impulse, I'm Eduardo, a future ML engineer, I just want to report an issue I found. The c++ library downloaded from my project has an inconsistency in the ./edge-impulse-sdk/cmake/utils.cmake file. This issue generates an infinite build loop, it seems it has a hidden character that doesn't allow the reading of the file. I fixed that using the same file from firmware-espressif-esp32 repo, and the issue isn't present anymore.

**Comment by ShawnHymel** [comment]
More info from user. Might be specific to ESP32:

> The loop happened because the utils.cmake file wasn't processed right during the build process, I,m working with the esp32 platform building the project with [idf.py](http://idf.py/) build command on windows, the weird thing here is that today trying to replicate the issue, now it works fine. I just don't know, If I find the mistake I can share it with you, meanwhile I will share the file that at the beginning I had the issue. The two files are identical in the text content but there is a little difference
> 
> $ cmp utils_bad.cmake utils_good.cmake
> utils_bad.cmake utils_good.cmake differ: byte 50, line 1
> 
> Now my build process works with both versions of the files but at the beginning it didn't, weird things, maybe you can skip this issue

**Comment by AIWintermuteAI** [comment]
Closing as reported resolved by user. Feel free to re-open if issue persists.

**Comment by hasheddan** [comment]
Somewhat randomly stumbled upon this issue, but just dropping a note here that if anyone runs into this, it is likely due to generating the SDK in the Edge Impulse console, and having files with a modified datetime in the future due to timezone differences. This explains why the original poster suddenly found the build working the next day. Issue can be addressed by `touch`'ing all files to update their modified timestamp.
